language: c
install: make get-deps
before_install:
    - sudo apt-get update
    - sudo apt-get install -y check
compiler: 
    - gcc
script: 
    gcc -o -g test_main dictionary.c dictionary.h spell.c test_main.c -Wall -lcheck -lm -lrt -lpthread -lsubunit
    - make
    - ./test_main 
   
